### ISSUE TITLE
Preserve url problem

### ISSUE THREAD

**Issue by mkraha** [perseids-tools/react-router-i18n#16]
Hi, 
Does preserve link work like you mentioned here or we have add something to work ?
[preserve links](https://github.com/perseids-tools/react-router-i18n#links)

Thank you!

**Comment by mkraha** [comment]
Anyone?!

**Comment by zfletch** [comment]
You can see the way links work in the [demo site](https://perseids-tools.github.io/react-router-i18n)  (code [here](https://github.com/perseids-tools/react-router-i18n/blob/master/src/demo/App.js)). As described in the README, you must import `Link` from `'react-router-i18n'` and the link must be inside a route that receives the `locale` param.

If you've found a bug, please provide a code sample of a minimal reproduction. That will make it easier to diagnose the problem.

**Comment by mkraha** [comment]
@zfletch I did re-code followed by your demo (App.js) which is working now. Thank you!!

How to reload Axios response after changes the language?

**Comment by mkraha** [comment]
I did following and it's worked.
```
componentDidUpdate(prevProps) {
    	const { locale } = this.props.match.params;
    	if(prevProps.match.params.locale !== locale) {
    		const params = {
	    		lang: this.Capitalize(locale)
	    	}

	    	axios.get(...)
    	}
}
```
