### ISSUE TITLE
[object Object] appearing in link attributes

### ISSUE THREAD

**Issue by iwazaru** [perseids-tools/react-router-i18n#17]
react-router-i18n seems to inject what I think are router props in the generated links attributes.

Here is some code that reproduces the problem:

```jsx
import { NavLink as RouterNavLink } from 'react-router-dom';
import { NavLink as I18nNavLink } from 'react-router-i18n';

export default function Header() {
  return (
    <nav>
        <RouterNavLink to="/">Home</RouterNavLink>
        <I18nNavLink to="/">Home</I18nNavLink>
    </nav>
  )
}
```

### Expected behavior:

Generated HTML should be the same except for the locale part of the url:

```html
<a aria-current="page" class="active" href="/">Home</a>
<a aria-current="page" class="active" href="/en/">Home</a>
```

### Actual behavior:

`match` and `history` attributes are showing up in the i18n link.

```html
<a aria-current="page" class="active" href="/">Home</a>
<a aria-current="page" class="active" match="[object Object]" history="[object Object]" href="/en/">Home</a>
```

I'm using:

> react@16.12.0
> react-router@5.1.2
> react-router-i18n@0.1.2

This is not a big problem per se as it doesn't break routing and navigation, but I fear it might harm SEO by generating invalid HTML. 

Thanks!

**Comment by zfletch** [comment]
Thanks @iwazaru for reporting the issue! It looks like we may want to exclude the other React Router props the same way we exclude the [staticContext](https://github.com/perseids-tools/react-router-i18n/blob/499e23bf0d38fc060ff214fc0fb922721821b0f1/src/lib/components/I18n/withLocale.js#L8) prop.

I will start working on a fix.

**Comment by zfletch** [comment]
New version [published](https://www.npmjs.com/package/react-router-i18n?activeTab=versions).
