### ISSUE TITLE
Page not found 

### ISSUE THREAD

**Issue by AhmadBehzadi** [perseids-tools/react-router-i18n#22]
Hi
I used the demo template.
When I use 

```
<Route path="*">
    <NotFound />
</Route>
```
or
```
<Route>
     <NotFound />
</Route>
```

for `Not found` URLs it seems the component is showing in all routes. Also currently all undeclared URLs are going to  home page. What is the solution for `Page not found` ?

**Comment by zfletch** [comment]
I can't be sure without more information, but it looks you need to use the [<Switch>](https://reactrouter.com/core/api/Switch) component:

```
<Switch>
  <Route path="/home">
    <Home />
  <Route>
    <NotFound />
  </Route>
</Switch>
```

**Comment by saaaaalll2020** [comment]
hi

`const App = () => (
  <Router basename={process.env.PUBLIC_URL}>
    <Route path={base} component={Header} />
    <Switch>
      <Route exact path={base} component={Home} />
      <Route path={`${base}/about`} component={About} />
      <Route path={`${base}/topics`} component={Topics} />
      <Route>
        <NotFound />
      </Route>
    </Switch>
  </Router>
);`

not found works for home page when route is wrong but does not work for internal pages.
work: http://localhost:3000/dkfdfklhgg
not work: http://localhost:3000/about/grtggtrty

**Comment by saaaaalll2020** [comment]
`const App = () => (
  <Router basename={process.env.PUBLIC_URL}>
    <Route path={base} component={Header} />
    <Switch>
      <Route exact path={base} component={Home} />
      <Route path={`${base}/about`} component={About} />
      <Route path={`${base}/topics`} component={Topics} />
      <Route>
        <NotFound />
      </Route>
    </Switch>
  </Router>
);`

**Comment by saaaaalll2020** [comment]
`
const App = () => (
  <Router basename={process.env.PUBLIC_URL}>
    <Route path={base} component={Header} />
    <Switch>
      <Route exact path={base} component={Home} />
      <Route path={`${base}/about`} component={About} />
      <Route path={`${base}/topics`} component={Topics} />
      <Route>
        <NotFound />
      </Route>
    </Switch>
  </Router>
);
`

**Comment by saaaaalll2020** [comment]
`const App = () => (
  <Router basename={process.env.PUBLIC_URL}>
    <Route path={base} component={Header} />
    <Switch>
      <Route exact path={base} component={HomePage} />
      <Route path={`${base}/about`} component={About} />
      <Route path={`${base}/topics`} component={Topics} />
      <Route>
        <NotFound />
      </Route>
    </Switch>
    <Route path={base} component={Footer} />
  </Router>
);
`

**Comment by saaaaalll2020** [comment]
```
const App = () => (
  <Router basename={process.env.PUBLIC_URL}>
    <Route path={base} component={Header} />
    <Switch>
      <Route exact path={base} component={HomePage} />
      <Route path={`${base}/about`} component={About} />
      <Route path={`${base}/topics`} component={Topics} />
      <Route>
        <NotFound />
      </Route>
    </Switch>
    <Route path={base} component={Footer} />
  </Router>
);
```

**Comment by saaaaalll2020** [comment]
hi
```
const App = () => (
  <Router basename={process.env.PUBLIC_URL}>
    <Route path={base} component={Header} />
    <Switch>
      <Route exact path={base} component={HomePage} />
      <Route path={`${base}/about`} component={About} />
      <Route path={`${base}/topics`} component={Topics} />
      <Route>
        <NotFound />
      </Route>
    </Switch>
    <Route path={base} component={Footer} />
  </Router>
);
```
not found works for home page when route is wrong but does not work for internal pages.
work: http://localhost:3000/dkfdfklhgg
not work: http://localhost:3000/about/grtggtrty

**Comment by zfletch** [comment]
@saaaaalll2020 I recommend reading the [React Router](https://reactrouter.com/web/guides/quick-start) documentation. Your issue is unrelated to `react-router-i18n`.

In this case the path `/about` matches. If you do not want `/about/a/b/c/d/` to match, but only `/about`, then the route needs to contain an `exact`: `<Route exact path={`${base}/about`} component={About} />`
