### ISSUE TITLE
How to use with SSR?

### ISSUE THREAD

**Issue by rchavik** [perseids-tools/react-router-i18n#23]
Getting the following error when building:

```
ReferenceError: window is not defined
    at Object.<anonymous> (../node_modules/react-router-i18n/build/index.js:1:401)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack:///external_%22react-router-i18n%22?:1:18)
```

I tried the following workaround:

```
diff --git a/config/webpack.config.prod.js b/config/webpack.config.prod.js
index c3e2686..dc117c2 100644
--- a/config/webpack.config.prod.js
+++ b/config/webpack.config.prod.js
@@ -105,6 +105,7 @@ module.exports = {
   devtool: shouldUseSourceMap ? 'source-map' : false,
   // In production, we only want to load the app code.
   entry: [paths.appLibIndexJs], // CRL: update entry
+  target: 'node',
   output: {
     // CRL: Updated whole block with library specific info
     path: paths.appBuild,
```

and things seem to work. Is this a correct solution?

**Comment by zfletch** [comment]
I have not tested the library with an app that does server-side rendering, but there is no reason it shouldn't work.

Could you share more details about your setup? Are you using `create-react-app` and default configuration? An ejected `create-react-app` application? Or do you have a custom Webpack configuration? Is the change in `webpack.config.prod.js` in your own application or did you clone `react-router-i18n` and make the change in that repository?

**Comment by rchavik** [comment]
It was based unejected create-react-app.

The change I pasted above was in a clone of `react-router-i18n`. Ran the build and then copied the resulting `build/index.js` to the app node_modules/react-router-i18n/

**Comment by rchavik** [comment]
Maybe the correct approach would be to offer [multiple targets](https://webpack.js.org/concepts/targets/#multiple-targets)?  I'm not quite sure how it would affect library users though.

**Comment by rchavik** [comment]
FYI I successfully built this lib with multiple targets, but i could not use it without changing `react-router-i18n` package.json `main` config to `index.node.js`. So that approach might not be really useful in this case. Might as well implicitly define `node` as target.

**Comment by zfletch** [comment]
It looks like it is related to [this](https://github.com/webpack/webpack/issues/6522) Webpack issue. Fortunately, there may be an easy fix. According to the [docs](https://webpack.js.org/configuration/output/#outputglobalobject), adding `globalObject: 'this'` will allow the library to work both in the browser and with server side rendering.

I tested it in a browser app and it worked. If you add `globalObject: 'this'` instead of `target: 'node',` and test it in your application, does it work? If that does fix, I will publish a new version.

Thank you for creating this issue and helping debug it!

**Comment by rchavik** [comment]
Thank you,

I tested adding `globalObject: 'this'` to `output` config does work and works for both normal cra and ssr modes.

**Comment by zfletch** [comment]
Great, I've uploaded a new version (`1.0.1`) to [npm](https://www.npmjs.com/package/react-router-i18n/v/1.0.1) with the fix.
